### ISSUE TITLE
GAP Include bug

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-packages/img#4]
Hi, I had the following bug report given to me. I don't know how to build `img`, so I can't look into it myself.

here is another issue,  which arose when I tried to install the package IMG by Laurent Bartholdi:  at some point the linker complained about

/home/jung/programs/gap4r8/src/system.h:1056:1: error: unknown type name 'sigjmp_buf'
extern syJmp_buf AlarmJumpBuffer;

--- The relevant part of  "system.h"  seems to be

#include        <setjmp.h>      /* jmp_buf, setjmp, longjmp        */
#if HAVE_SIGSETJMP
...
#define syJmp_buf sigjmp_buf
#else
...

--- and my <setjmp.h> reads

#ifdef  __USE_POSIX
...
typedef struct __jmp_buf_tag sigjmp_buf[1];
...
#endif /* Use POSIX.  */

So for this to work,   HAVE_SIGSETJMP  must not be defined unless __USE_POSIX  is defined as well.  I have checked the file "config.h" generated by IMG and it did not define  HAVE_SIGSETJMP . So I suppose it was defined by GAP before,  without defining __USE_POSIX ?  Probably there are compatibility issues with  gcc as well;  my version is
gcc version 4.8.1 20130909 [gcc-4_8-branch revision 202388] (SUSE Linux) ,

I worked around this issue by defining   __USE_POSIX  manually ...

**Comment by laurentbartholdi** [comment]
This problem probably disappeared by itself. If it shows up again, reopen.
